itunes input feature
brinda-wednesday/itunes pull request #1
Opened 2021-08-13 11:09 UTC by brinda-wednesday

### Ticket Link

---

### Related Links

---

### Description
Added an iTunes container with an input element used to search the song name
---

### Steps to Reproduce / Test

---

### GIF's

---

2021-08-16 04:16 UTC, alichherawalla commented on app/containers/HomeContainer/index.js
> +    console.log(loaded);
remove console logs

2021-08-16 15:37 UTC, alichherawalla commented on app/containers/ITunes/index.js
> +    max-width: 1000px;
use em instead of px

2021-08-16 15:39 UTC, alichherawalla commented on app/containers/ITunes/index.js
> +    background-color: #e5e7eb;
const colors

2021-08-16 15:39 UTC, alichherawalla commented on app/containers/ITunes/index.js
> +    max-width: 1000px;
we're using max-width way too much. shouldn't width: 100% just suffice?

2021-08-16 15:40 UTC, alichherawalla commented on app/containers/ITunes/index.js
> +                  avatar={<Avatar src={item.artworkUrl100} style={{ width: '75px', height: '75px' }} />}
use styled-components. Don't use the style prop

2021-08-16 15:40 UTC, alichherawalla commented on app/containers/ITunes/index.js
> +                <audio controls style={{ width: '250px' }}>
styled-components

2021-08-17 19:48 UTC, alichherawalla commented on app/containers/ITunes/index.js
> +    const loaded = get(songData, 'results', null) || songError;
```
 const loaded = get(songData, 'results', songError);
```


if `loaded` is dependent on both `songData` as well as `songError` the dependency array should have both of them.

```
  }, [songData, songError]);
```

2021-08-17 19:53 UTC, alichherawalla commented on app/containers/ITunes/index.js
> +    const items = get(songData, 'results', []);
```
const items = get(songData, 'results', []);
return (
<If condition={items?.length || loading}>
...
...
</If>
```

2021-08-17 19:54 UTC, alichherawalla commented on app/containers/ITunes/selectors.js
> +export const selectSongData = () => createSelector(selectITunesDomain, (substate) => get(substate, 'songData', null));
don't use the third parameter for the lodash.get here. We don't need to supply it a default value as null. 

```
createSelector(selectITunesDomain, (substate) => get(substate, 'songData'));
```

please replicate for all selectors

2021-08-17 19:54 UTC, alichherawalla commented on app/containers/ITunes/tests/index.test.js
> +  it('should call dispatchSongs on change', async () => {
add more tests to ensure that if data is provided the grid is rendered correctly

2021-08-17 19:55 UTC, alichherawalla commented on app/containers/ITunes/tests/index.test.js
> +  it('should call dispatchSongs on change', async () => {
number of children rendered in the grid are correct

2021-08-17 19:55 UTC, alichherawalla commented on app/utils/routeConstants.js
> +    route: '/itunes',
delete the package-lock.json. we use yarn

2021-08-18 06:13 UTC, rameez-wed requested changes

2021-08-18 06:13 UTC, rameez-wed commented on app/components/For/index.js
> +  isrow: true
Please use camelCase. I think isRow was correct

2021-08-18 06:13 UTC, rameez-wed commented on app/containers/ITunes/index.js
> +  const items = get(songData, 'results', []);
Move these to the top

2021-08-18 06:13 UTC, rameez-wed commented on app/components/ItunesCard/index.js
> +export function ItunesCard({ songTitle, imgSrc, songArtist, audioSrc, trackId }) {
iTunesCard instead of ItunesCard

2021-08-18 06:13 UTC, rameez-wed commented on app/containers/ITunes/index.js
> +ITunes.propTypes = {
iTunes instead of ITunes

2021-08-18 06:34 UTC, rameez-wed approved these changes

2021-08-18 06:35 UTC, merged